services:
  - type: web
    name: scale-ai-clone
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scale_ai_platform.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
