services:
  - type: web
    name: scale-ai-clone
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
      python manage.py collectstatic --noinput
    startCommand: gunicorn scale_ai_platform.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: scale-ai-clone-1.onrender.com,scale-ai-clone.onrender.com,.onrender.com
